---
# This playbook update the agents in the servers.
  
- name: Configurations to "remote" host
  hosts: all
  become: yes
  become_user: root
  become_method: sudo
  vars:
    yavire_user: yavagent
    yavire_group: yavire
    yavire_directory: /opt/krb/yavire

  tasks:
    - name: Ansible fact Yavire User
      debug:
         msg: "{{ yavire_user }}"

    - name: Ansible fact for Playbok_dir
      debug:
         msg: "{{ playbook_dir }}"

    - name: synchronize  {{ playbook_dir }}/roles/yavire-agent/files/agent/scripts to {{ yavire_directory }}/agent}
      synchronize:
        src: "{{ playbook_dir }}/roles/yavire-agent/files/agent/scripts"
        dest: "{{ yavire_directory }}/agent"
        use_ssh_args: yes

    - name: Change permissions 
      file: 
        dest: "{{ yavire_directory }}/agent"
        owner: "{{ yavire_user }}"
        group: "{{ yavire_group }}"
        mode: 0775
        recurse: yes
      

    - name: Execute yavireWeeklyInventory.pl and yavireDailyInventory.sh script
      block:
        - name : Execute Weekly Inventory
          command: "{{ yavire_directory }}/agent/scripts/inventory/yavireWeeklyInventory.sh"
          register: yav_weekly

        - name : Execute Daily Inventory
          command: "{{ yavire_directory }}/agent/scripts/inventory/yavireDailyInventory.sh"
          register: yav_daily


        - debug: msg="{{ yav_weekly.stdout }}"

      become: yes
      become_user: "{{ yavire_user }}"

