---
# This playbook contains yavire agent actions that will be run on "remote" host.

- name: YAVIRE-COMMONS | Install util packages
  package: 
    name: "{{ item }}"
    state: present
  with_items:
    - net-tools
  tags:
    - yavire-common
    - wget
    - unzip
    - zip
    - nano
    - curl

- name: YAVIRE-COMMONS | Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present
  tags:
    - yavire-common

- name: YAVIRE-COMMONS | Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
  tags:
    - yavire-common

- name: YAVIRE-COMMONS | Add sudoers users to wheel group
  user: 
    name: "{{ yavire_user }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
  tags:
    - yavire-common
 
# sudo groupadd yavire
- name: YAVIRE-COMMONS | Create "yavire" group
  group:
    name: "{{ yavire_group }}"
    state: present
  tags:
    - yavire-common


- name: YAVIRE-COMMONS | Add the user yavire agent with a bash shell, appending the group 'yavire'  to the user's groups
  user:
    name: "{{ yavire_user }}"
    shell: /bin/bash
    groups: "{{ yavire_group }}"
    append: yes
  tags:
    - yavire-common

- name: YAVIRE-COMMONS | Creates yavire directory 
  file:
    path: "{{ yavire_directory }}"
    state: directory
    owner: "{{ yavire_user }}"
    group: "{{ yavire_group }}"
    mode: 0775
    recurse: yes
  tags:
     - yavire-common

#- name: YAVIRE-COMMONS | EC2_INSTANCE 
#  ec2_instance_facts:
#    instance_ids:
#      - i-03c0e223cfd412e3d
#  delegate_to: 127.0.0.1
