---
# This playbook contains all actions that will be run on "local" host.
  
# sudo apt-get update
#- name: Update apt packages
#  apt:
#    update_cache: yes
#  tags:
#    - system
  
# Import yavire inventory tasks
- name: Install Yavire Inventorion on Master Server
  include_tasks: yavire-inventory.yml
  
